# Generated by Django 3.2.23 on 2023-12-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_models_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='models',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
