# Generated by Django 3.2.23 on 2023-12-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20231217_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='models'),
        ),
    ]
