# Generated by Django 3.2.23 on 2024-01-13 08:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20231217_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='model',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='model'),
        ),
    ]
