# Generated by Django 3.2.23 on 2024-01-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_models_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='model'),
        ),
    ]
