# Generated by Django 3.2.23 on 2024-01-13 12:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_models_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='model',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='auto'),
        ),
    ]
