# Generated by Django 3.2.23 on 2024-01-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_models_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='extension',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='model'),
        ),
    ]
